accounts/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup./', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('eatup.urls')),
    path('accounts/', include('accounts.urls')),
]

eatup/urls.py
from django.urls import path, include
from . import views

app_name = 'eatup'

urlpatterns = [
    path('', views.index, name='index'),
    path('shopping-cart/', views.shopping_cart, name='shopping-cart'),
    path('notification/', views.notification, name='notification'),
    path('user-info/', views.user_info, name='user-info'),
    path('scan/', views.scan, name='scan'),

    # api
    path('api/scan-item/', views.api_scan_item, name='api-scan-item'),
    #path('api/delete-item/<int:id>', views.api_delete_item, name='api-delete-item'),
]

eatup/models.py
from django.db import models

# Create your models here.

pos/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import User


# Create your models here.
class Pos(models.Model):
    name = models.CharField(max_length=50)
    price = models.IntegerField()
    best_effort = models.DateField(null=True, blank=True) # 賞味期限
    used_by = models.DateField(null=True, blank=True) # 消費期限
    # 画像まだない

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cart')
    pos = models.ManyToManyField(Pos, blank=True)
    count = models.IntegerField(default=1)
    is_checked_out = models.BooleanField(default=False)

eatup/forms.py
from django import forms
from django.forms import fields
from .models import *
from pos.models import *

class ScanItemForm(forms.Form):
    pos_id = forms.CharField(max_length=40, required=True)

    def __init__(self, *args, **kwargs):
        super(ScanItemForm, self).__init__(*args, **kwargs)
        
    
    def get_scanning_pos_id(self):
        return self.data['pos_id']

class AddCartForm(forms.ModelForm):
    class Meta:
        model = Cart
        fields = ['user', 'pos']

    def __init__(self, *args, **kwargs):
        super(AddCartForm, self).__init__(*args, **kwargs)

accounts/views.py
from django.shortcuts import render

# Create your views here.

def signup(request):
    return render(request, 'regiatration/login.html')

eatup/views.py
from django.shortcuts import render, redirect
from pos.models import *
from accounts.models import *
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import ScanItemForm, AddCartForm

# Create your views here.

TAX = 0.08

def index(request):
    return render(request, 'eatup/index.html')

@login_required
def shopping_cart(request):
    cart = Cart.objects.filter(user=request.user, is_checked_out=False)
    subtotal = 0
    for item in cart:
        for pos in item.pos.all():
            subtotal += pos.price * item.count
    params = {
        'cart': cart,
        'subtotal': subtotal,
        'tax': TAX * 100,
        'total': int(subtotal * (1 + TAX)),
    }
    if request.method == 'POST':
        for cart in cart:
            cart.is_checked_out = True
            cart.save()
        return redirect('eatup:index')
    return render(request, 'eatup/shoppingcart.html', params)

@login_required
def notification(request):
    history = Cart.objects.filter(user=request.user, is_checked_out=True)
    params = {
        'history': history,
    }
    return render(request, 'eatup/notification.html', params)

@login_required
def user_info(request):
    user = User.objects.get(username=request.user)
    params = {
        'user': user,
    }
    return render(request, 'eatup/usermenu.html', params)

@login_required
def scan(request):
    form = ScanItemForm()
    params = {
        'form': form,
    }
    return render(request, 'eatup/scan.html', params)

# api

def api_scan_item(request):
    pos_id = request.POST.get('pos_id')
    get_pos = Pos.objects.get(pk=pos_id)
    cart = Cart.objects.create(user=request.user)
    cart.pos.add(get_pos)

    return redirect('eatup:shopping-cart')

pos/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
    <style>
        html,
        body {
            max-width: 100%;
            ;
        }

        header {
            height: 4.5rem;
        }

        footer {
            height: 4rem;
            box-shadow: 0 -0.5rem 1rem rgba(0, 0, 0, .15) !important;
        }

        footer i {
            font-size: 1.2rem;
        }

        main {
            padding-top: 5rem;
            padding-bottom: 5rem;
            width: 100%;
        }

        .o-summary-table td {
            border: none;
        }

        .o-userinfo-table td {
            border: none;
        }

        td p {
            margin-bottom: 0;
        }

        .o-scan-btn {
            position: fixed;
            right: 1rem;
            bottom: 5rem;
            border-radius: 2rem;
        }

        .o-profile-img {
            border-radius: 50%;
        }
    </style>
    <title>{% block title %}{% endblock %} - EatUP</title>
</head>

<body>
    <header class="shadow d-flex align-items-end w-100 fixed-top">
        <div class="mx-auto">
            <h5 class="fw-bold">EatUP</h5>
        </div>
    </header>
    <main class="container-fluid vh-100">
        {% block content %}{% endblock %}
    </main>

    <footer class="d-flex align-items-center justify-content-around w-100 fixed-bottom">
        <div>
            <a href="{% url 'eatup:index' %}" class="btn"><i class="bi bi-house"></i>
                <br><span class="small text-muted">Home</span></a>
        </div>
        <div>
            <a href="{% url 'eatup:shopping-cart' %}" class="btn"><i class="bi bi-cart"></i><br><span
                    class="small text-muted">Cart</span></a>
        </div>
        <div>
            <a href="{% url 'eatup:notification' %}" class="btn"><i class="bi bi-bell"></i><br><span
                    class="small text-muted">Notice</span></a>
        </div>
        <div>
            <a href="{% url 'eatup:user-info' %}" class="btn"><i class="bi bi-person"></i><br><span
                    class="small text-muted">User</span></a>
        </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
    </script>
</body>

</html>

templates/eatup/index.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
Home
{% endblock %}

{% block content %}
<head>
    <link rel="stylesheet" href="{% static 'hide-scroll.css' %}">
</head>
<div class="d-flex align-items-center h-100 o-home">
    <div>
        <div class="mb-5 py-4">
            <div id="carouselIndicators" class="carousel carousel-dark slide" data-bs-ride="carousel">
                
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <img src="{% static 'media/shopping1.png' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'media/shopping2.png' %}" class="d-block w-100" alt="...">
                    </div>
                    <div class="carousel-item">
                        <img src="{% static 'media/shopping3.png' %}" class="d-block w-100" alt="...">
                    </div>
                </div>
            </div>
        </div>
        
        <div>
            <a href="{% url 'eatup:shopping-cart' %}" class="btn btn-lg btn-primary d-block">Start Shopping Smart</a>
        </div>
    </div>
</div>
{% endblock %}

templates/eatup/notification.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
notification
{% endblock %}

{% block content %}
<div>
    <div>
        <table class="table">
            <tbody>
                {% for item in history %}
                {% for pos in item.pos.all %}
                <tr>
                    <td style="width: 90px;">
                        <img src="{% static 'media/example-apple.jpg' %}" class="img-thumbnail" alt="food1" width="90"
                            height="90">
                    </td>
                    <td class="align-middle">
                        <h6 class="mb-1 fw-bold">{{pos.name}}</h6>
                        {% if pos.used_by %}
                        <p class="mb-0">Used By: {{pos.used_by | date:'Y/m/d'}}</p>
                        {% else %}
                        <p class="mb-0">Best Effort: {{pos.best_effort | date:'Y/m/d'}}</p>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/eatup/scan.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
Scan QR
{% endblock %}

{% block content %}
<div id="loadingMessage">
    Wait Just a Minutes...<br>
    (You need allow camera access to scan QR code.)
</div>
<div>
  <canvas id="canvas" style="width:100%;"></canvas>
</div>
<div id="output">
  <div id="outputMessage"></div>
  <div class="w-100" style="word-break: break-all;">
      <p id="outputData"></p>
  </div>
</div>
<form class="d-none" action="{% url 'eatup:api-scan-item' %} " method="POST">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit" id="pos-id-button">send</button>
</form>
<script src="https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.min.js"></script>
<script>
  var video = document.createElement("video");
  var canvasElement = document.getElementById("canvas");
  var canvas = canvasElement.getContext("2d");
  var loadingMessage = document.getElementById("loadingMessage");
  var outputContainer = document.getElementById("output");
  var outputMessage = document.getElementById("outputMessage");
  var outputData = document.getElementById("outputData");

  function drawLine(begin, end, color) {
    canvas.beginPath();
    canvas.moveTo(begin.x, begin.y);
    canvas.lineTo(end.x, end.y);
    canvas.lineWidth = 4;
    canvas.strokeStyle = color;
    canvas.stroke();
  }

  // Use facingMode: environment to attemt to get the front camera on phones
  navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" } }).then(function(stream) {
    video.srcObject = stream;
    video.setAttribute("playsinline", true); // required to tell iOS safari we don't want fullscreen
    video.play();
    requestAnimationFrame(tick);
  });

  function tick() {
    loadingMessage.innerText = "⌛ Loading video..."
    if (video.readyState === video.HAVE_ENOUGH_DATA) {
      loadingMessage.hidden = true;
      canvasElement.hidden = false;
      outputContainer.hidden = false;

      canvasElement.height = video.videoHeight;
      canvasElement.width = video.videoWidth;
      canvas.drawImage(video, 0, 0, canvasElement.width, canvasElement.height);
      var imageData = canvas.getImageData(0, 0, canvasElement.width, canvasElement.height);
      var code = jsQR(imageData.data, imageData.width, imageData.height, {
        inversionAttempts: "dontInvert",
      });
      if (code) {
        drawLine(code.location.topLeftCorner, code.location.topRightCorner, "#FF3B58");
        drawLine(code.location.topRightCorner, code.location.bottomRightCorner, "#FF3B58");
        drawLine(code.location.bottomRightCorner, code.location.bottomLeftCorner, "#FF3B58");
        drawLine(code.location.bottomLeftCorner, code.location.topLeftCorner, "#FF3B58");
        outputMessage.hidden = true;
        outputData.parentElement.hidden = false;
        outputData.innerText = code.data;
      } else {
        outputMessage.hidden = false;
        outputData.parentElement.hidden = true;
      }
    }
    requestAnimationFrame(tick);
  }
</script>

<script>

var observer = new MutationObserver(function(){
  var pos_id = document.getElementById('outputData').innerText;
  document.getElementById("id_pos_id").value = pos_id;
  document.getElementById("pos-id-button").click();
  observer.disconnect();
});

const elem = document.getElementById('outputData');
 
/** 監視時のオプション */
const config = { 
  attributes: true, 
  childList: true, 
  characterData: true 
};
 
/** 要素の変化監視をスタート */
observer.observe(elem, config);
</script>
{% endblock %}

templates/eatup/shoppingcart.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
Shopping
{% endblock %}

{% block content %}
<table class="table">
    <tbody>
        {% for item in cart %}
        {% for pos in item.pos.all %}
        <tr>
            <td style="width: 90px;">
                <img src="{% static 'media/example-apple.jpg' %}" class="img-thumbnail" alt="food1" width="90"
                    height="90">
            </td>
            <td class="align-middle">
                <h6 class="fw-bold mb-1">{{pos.name}}</h6>
                <small class="text-muted m-0">{{pos.price}} Yen</small>
            </td>
            <td class="align-middle" style="width: 32px;">
                <div class="d-flex align-items-center">
                    <small class="text-muted m-0 me-3">{{item.count}}</small>
                    <button type="submit" class="btn btn-sm btn-danger"><i class="bi bi-trash2"></i></button>
                </div>
            </td>
        </tr>
        {% endfor %}
        {% endfor %}
    </tbody>
</table>
<!-- order summary -->
<div class="px-2">
    <h6>Order Summary</h6>
    <table class="table o-summary-table">
        <tbody>
            <tr>
                <td>
                    <small class="text-muted fw-bold">Subtotal</small>
                </td>
                <td class="text-end">
                    <p class="fw-bold">{{subtotal}} Yen</p>
                </td>
            </tr>
            <tr>
                <td>
                    <small class="text-muted fw-bold">Tax</small>
                </td>
                <td class="text-end">
                    <p class="fw-bold">{{tax}} %</p>
                </td>
            </tr>
            <tr>
                <td>
                    <small class="text-muted fw-bold">Order Total</small>
                </td>
                <td class="text-end">
                    <p class="fw-bold">{{subtotal}} Yen</p>
                </td>
            </tr>
            <td>
                <small class="text-muted fw-bold">Total</small>
            </td>
            <td class="text-end">
                <h4 class="fw-bold">{{total}} Yen</h4>
            </td>
        </tbody>
    </table>
    <div>
        <form action="{% url 'eatup:shopping-cart' %}" method="POST">
            {% csrf_token %}
            <button class="btn btn-lg w-100 btn-dark"><i class="bi bi-check2 pe-2"></i>Proceed to
                Checkout</button>
        </form>
    </div>
</div>

<a href="{% url 'eatup:scan' %}" class="btn btn-lg btn-primary px-4 py-2 o-scan-btn"><i
        class="bi bi-upc-scan pe-2"></i>Scan</a>
{% endblock %}

templates/eatup/usermenu.html
{% extends '../base.html' %}
{% load static %}

{% block title %}
User Info
{% endblock %}

{% block content %}
<div>
    <div>
        <table class="table">
            <tbody class="o-userinfo-table">
                <tr>
                    <td class="w-100">
                        <img src="{% static 'media/user-img.png' %}" class="img-thumbnail o-profile-img" alt="food1" width="90"
                            height="90">
                    </td>
                    <td class="align-middle" >
                        <a href="#" class="btn btn-sm btn-secondary"><i class="bi bi-pen"></i></a>
                    </td>
                </tr>
            </tbody>
        </table>
        <div class="px-2 mb-3">
            <h2 class="fw-bold mb-0">{{user.username}}</h2>
            <small class="text-primary fw-bold">{{user.email}}</small>
        </div>
        <div class="px-2">
            <p class="fw-bold mb-0">Account Setting</p>
            <table class="table">
                <tbody>
                    <tr>
                        <td class="w-100 ps-0">
                            <small>User Profile</small>
                        </td>
                        <td class="pe-0">
                            <i class="bi bi-chevron-right"></i>
                        </td>
                    </tr>
                    <tr>
                        <td class="w-100 ps-0">
                            <small>Order History</small>
                        </td>
                        <td class="pe-0">
                            <i class="bi bi-chevron-right"></i>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="text-center">
            <a href="#" class="btn btn-secondary"><i class="bi bi-box-arrow-right pe-2"></i>Sign out</a>
        </div>
    </div>
</div>
{% endblock %}